/**
 * Visit workflow states — operational backbone of MediCentral.
 * PATIENT = GLOBAL, VISIT = LOCAL (state is per HospitalVisit).
 */

export const WORKFLOW_STATES = {
  REGISTERED: 'REGISTERED',
  WAITING_FOR_PA: 'WAITING_FOR_PA',
  PA_REVIEW: 'PA_REVIEW',
  WAITING_FOR_DOCTOR: 'WAITING_FOR_DOCTOR',
  IN_CONSULTATION: 'IN_CONSULTATION',
  LAB_REQUIRED: 'LAB_REQUIRED',
  LAB_PENDING: 'LAB_PENDING',
  LAB_COMPLETED: 'LAB_COMPLETED',
  ADMISSION_REQUIRED: 'ADMISSION_REQUIRED',
  ADMITTED: 'ADMITTED',
  UNDER_OBSERVATION: 'UNDER_OBSERVATION',
  READY_FOR_SURGERY: 'READY_FOR_SURGERY',
  SURGERY_REQUIRED: 'SURGERY_REQUIRED',
  SURGERY_SCHEDULED: 'SURGERY_SCHEDULED',
  IN_SURGERY: 'IN_SURGERY',
  POST_SURGERY: 'POST_SURGERY',
  PHARMACY_PENDING: 'PHARMACY_PENDING',
  BILLING_PENDING: 'BILLING_PENDING',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  READY_FOR_DISCHARGE: 'READY_FOR_DISCHARGE',
  DISCHARGED: 'DISCHARGED',
};

export const WORKFLOW_STATE_LIST = Object.values(WORKFLOW_STATES);

/**
 * Legacy HospitalVisit.status (Mongo) — kept during migration.
 */
export const LEGACY_VISIT_STATUS = ['waiting', 'consultation', 'completed', 'emergency'];

/** Approximate mapping legacy → workflow (foundation only) */
export const LEGACY_STATUS_TO_WORKFLOW = {
  waiting: WORKFLOW_STATES.WAITING_FOR_DOCTOR,
  consultation: WORKFLOW_STATES.IN_CONSULTATION,
  completed: WORKFLOW_STATES.DISCHARGED,
  emergency: WORKFLOW_STATES.WAITING_FOR_DOCTOR,
};

/** Department pipeline order for documentation and future orchestration */
/** Phase 1 primary pipeline */
export const PHASE1_PIPELINE = [
  WORKFLOW_STATES.REGISTERED,
  WORKFLOW_STATES.WAITING_FOR_PA,
  WORKFLOW_STATES.PA_REVIEW,
  WORKFLOW_STATES.WAITING_FOR_DOCTOR,
  WORKFLOW_STATES.IN_CONSULTATION,
];

export const WORKFLOW_PIPELINE = [
  { step: 'reception', state: WORKFLOW_STATES.REGISTERED, next: WORKFLOW_STATES.WAITING_FOR_PA },
  { step: 'doctor_pa', state: WORKFLOW_STATES.WAITING_FOR_PA, next: WORKFLOW_STATES.PA_REVIEW },
  { step: 'doctor_pa_review', state: WORKFLOW_STATES.PA_REVIEW, next: WORKFLOW_STATES.WAITING_FOR_DOCTOR },
  { step: 'doctor', state: WORKFLOW_STATES.WAITING_FOR_DOCTOR, next: WORKFLOW_STATES.IN_CONSULTATION },
  { step: 'lab', state: WORKFLOW_STATES.LAB_REQUIRED, next: WORKFLOW_STATES.LAB_PENDING },
  { step: 'ward', state: WORKFLOW_STATES.ADMISSION_REQUIRED, next: WORKFLOW_STATES.PHARMACY_PENDING },
  { step: 'surgery', state: WORKFLOW_STATES.SURGERY_REQUIRED, next: WORKFLOW_STATES.PHARMACY_PENDING },
  { step: 'pharmacy', state: WORKFLOW_STATES.PHARMACY_PENDING, next: WORKFLOW_STATES.BILLING_PENDING },
  { step: 'billing', state: WORKFLOW_STATES.BILLING_PENDING, next: WORKFLOW_STATES.READY_FOR_DISCHARGE },
  { step: 'printing', state: WORKFLOW_STATES.READY_FOR_DISCHARGE, next: WORKFLOW_STATES.DISCHARGED },
];
