import Billing from '../../models/Billing.js';
import Doctor from '../../models/Doctor.js';
import { generateInvoiceNumber } from '../../utils/indiaHealthcare.js';

const DEFAULT_CONSULTATION = 500;

const categoryAmount = (category) => {
  const map = {
    pathology: 800,
    blood: 600,
    mri: 4500,
    ct: 3500,
    xray: 1200,
    other: 500,
  };
  return map[category] || 500;
};

/**
 * Auto-aggregate visit charges — no giant manual forms.
 */
export class VisitBillingService {
  static buildLineItems(visit, doctor) {
    const items = [
      {
        description: `${visit.department || 'General'} consultation`,
        amount: doctor?.consultationFee || DEFAULT_CONSULTATION,
        category: 'consultation',
      },
    ];

    (visit.labOrders || []).forEach((order) => {
      if (order.status !== 'completed' && order.status !== 'ordered' && order.status !== 'in_progress') return;
      items.push({
        description: `Lab — ${order.testName}`,
        amount: order.estimatedAmount || categoryAmount(order.category),
        category: 'lab',
      });
    });

    (visit.pharmacyFulfillment || [])
      .filter((p) => p.status === 'dispensed')
      .forEach((p) => {
        items.push({
          description: `Pharmacy — ${p.medicationName}`,
          amount: p.amount || 50,
          category: 'pharmacy',
        });
      });

    return items;
  }

  static async refreshVisitBill({ visit, patient }) {
    if (!visit.billingSummary?.billId) return null;
    const bill = await Billing.findById(visit.billingSummary.billId);
    if (!bill) return null;
    const doctor = visit.assignedDoctor ? await Doctor.findById(visit.assignedDoctor) : null;
    const items = this.buildLineItems(visit, doctor);
    const subtotal = items.reduce((s, i) => s + Number(i.amount || 0), 0);
    bill.items = items;
    bill.subtotal = subtotal;
    bill.totalAmount = subtotal;
    await bill.save();
    return bill;
  }

  static async ensureVisitBill({ visit, patient, createdBy }) {
    if (visit.billingSummary?.billId) {
      const existing = await Billing.findById(visit.billingSummary.billId);
      if (existing) return existing;
    }

    const doctor = visit.assignedDoctor
      ? await Doctor.findById(visit.assignedDoctor)
      : null;

    const items = this.buildLineItems(visit, doctor);
    const subtotal = items.reduce((s, i) => s + Number(i.amount || 0), 0);
    const invoiceNumber = await generateInvoiceNumber(Billing);

    const bill = await Billing.create({
      patient: patient._id || patient,
      visit: visit._id,
      invoiceNumber,
      items,
      subtotal,
      gstRate: 0,
      gstAmount: 0,
      totalAmount: subtotal,
      currency: 'INR',
      createdBy: createdBy?._id,
      notes: `Auto-generated for visit ${visit.tokenNumber || visit._id}`,
    });

    visit.billingSummary = { billId: bill._id, autoGenerated: true };
    await visit.save();

    return bill;
  }

  static async markPaid(billId, { amount, method, reference, receivedBy }) {
    const bill = await Billing.findById(billId);
    if (!bill) {
      const err = new Error('Bill not found');
      err.status = 404;
      throw err;
    }

    const payAmount = amount ?? bill.totalAmount - (bill.amountPaid || 0);
    bill.amountPaid = (bill.amountPaid || 0) + payAmount;
    bill.payments.push({ amount: payAmount, method: method || 'cash', reference, paidAt: new Date() });

    if (bill.amountPaid >= bill.totalAmount) bill.status = 'paid';
    else if (bill.amountPaid > 0) bill.status = 'partial';
    else bill.status = 'pending';

    await bill.save();
    return bill;
  }
}

export default VisitBillingService;
