import mongoose from 'mongoose';
import { WORKFLOW_STATE_LIST } from '../../shared/constants/workflow.js';

const hospitalVisitSchema = new mongoose.Schema(
  {
    patient: { type: mongoose.Schema.Types.ObjectId, ref: 'Patient', required: true },
    /** Multi-tenant scope (Phase 0 foundation) */
    tenant: { type: mongoose.Schema.Types.ObjectId, ref: 'HospitalTenant' },
    branch: { type: mongoose.Schema.Types.ObjectId, ref: 'Branch' },
    visitType: { type: String, enum: ['OP', 'IP'], default: 'OP' },
    tokenNumber: { type: String },
    department: { type: String, default: 'General Medicine' },
    /** Legacy queue status — preserved for existing dashboards */
    status: {
      type: String,
      enum: ['waiting', 'consultation', 'completed', 'emergency'],
      default: 'waiting',
    },
    /** Workflow engine state — operational backbone */
    workflowState: {
      type: String,
      enum: WORKFLOW_STATE_LIST,
      default: 'REGISTERED',
    },
    currentQueueType: { type: String },
    checkIn: { type: Date, default: Date.now },
    checkOut: { type: Date },
    assignedDoctor: { type: mongoose.Schema.Types.ObjectId, ref: 'Doctor' },
    notes: { type: String },
    priority: { type: String, enum: ['normal', 'urgent', 'critical'], default: 'normal' },
    isFollowUp: { type: Boolean, default: false },
    /** VIP pre-booked flow (Special Phase) */
    isPrebooked: { type: Boolean, default: false },
    estimatedWaitMinutes: { type: Number },
    paPrepNotes: { type: String },
    symptomNotes: { type: String },
    consultationNotes: { type: String },
    diagnosisSummary: { type: String },
    vitals: {
      bp: { type: String },
      pulse: { type: String },
      temperature: { type: String },
      spo2: { type: String },
      glucose: { type: String },
      respiratoryRate: { type: String },
      recordedAt: { type: Date },
    },
    vitalsLog: [
      {
        bp: String,
        pulse: String,
        temperature: String,
        spo2: String,
        glucose: String,
        respiratoryRate: String,
        recordedAt: { type: Date, default: Date.now },
        recordedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'Staff' },
        notes: String,
      },
    ],
    inpatient: {
      wardName: String,
      bedNumber: String,
      roomNumber: String,
      admissionType: { type: String, enum: ['planned', 'emergency'], default: 'planned' },
      admittedAt: Date,
      icu: { type: Boolean, default: false },
      observationNotes: String,
    },
    surgery: {
      procedureName: String,
      otRoom: String,
      surgeonName: String,
      scheduledAt: Date,
      preOpNotes: String,
      postOpNotes: String,
      status: {
        type: String,
        enum: ['required', 'scheduled', 'in_progress', 'completed'],
      },
    },
    pharmacyFulfillment: [
      {
        medicationName: { type: String, required: true },
        dosage: String,
        quantity: { type: Number, default: 1 },
        status: { type: String, enum: ['pending', 'dispensed'], default: 'pending' },
        dispensedAt: Date,
        amount: { type: Number, default: 0 },
      },
    ],
    nursingNotes: [
      {
        text: { type: String, required: true },
        authorName: String,
        author: { type: mongoose.Schema.Types.ObjectId, ref: 'Staff' },
        createdAt: { type: Date, default: Date.now },
      },
    ],
    discharge: {
      summary: String,
      generatedAt: Date,
      archivedAt: Date,
      packetUrl: String,
    },
    /** Open visit folder on patient timeline until discharge is completed */
    timelineOpen: { type: Boolean, default: true },
    timelineClosedAt: { type: Date },
    /**
     * Staff access + follow-up gating:
     * - While patient is with doctor, only doctor can see full history.
     * - After doctor submits a prescription, staff can proceed with follow-up/billing/discharge.
     */
    doctorSubmittedAt: { type: Date },
    hasDoctorPrescription: { type: Boolean, default: false },
    followUpRequired: { type: Boolean, default: false },
    dischargeRequested: { type: Boolean, default: false },
    labInstructions: { type: String },
    labOrders: [
      {
        testName: { type: String, required: true },
        category: {
          type: String,
          enum: ['pathology', 'blood', 'mri', 'ct', 'xray', 'other'],
          default: 'pathology',
        },
        instructions: { type: String },
        estimatedAmount: { type: Number, default: 0 },
        status: { type: String, enum: ['ordered', 'in_progress', 'completed'], default: 'ordered' },
      },
    ],
    billingSummary: {
      billId: { type: mongoose.Schema.Types.ObjectId, ref: 'Billing' },
      autoGenerated: { type: Boolean, default: false },
    },
  },
  { timestamps: true }
);

hospitalVisitSchema.index({ status: 1, checkIn: -1 });
hospitalVisitSchema.index({ workflowState: 1, checkIn: -1 });
hospitalVisitSchema.index({ tenant: 1, branch: 1, workflowState: 1 });
hospitalVisitSchema.index({ patient: 1, checkIn: -1 });
hospitalVisitSchema.index({ tokenNumber: 1 });

export default mongoose.model('HospitalVisit', hospitalVisitSchema);
